name: flutter_audio_desktop
description: A simple yet functional audio library for Flutter Desktop.
version: 0.0.1
author: alexmercerind
homepage: https://github.com/alexmercerind/flutter_audio_desktop
repository: https://github.com/alexmercerind/flutter_audio_desktop
documentation: https://github.com/alexmercerind/flutter_audio_desktop/README.md

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: any
  ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterAudioDesktopPlugin