name: flutter_audio_desktop
description: A simple yet functional audio library for Flutter Desktop. It can play MP3 files in your Flutter Desktop app.
version: 0.0.5
homepage: https://github.com/alexmercerind/flutter_audio_desktop
repository: https://github.com/alexmercerind/flutter_audio_desktop
documentation: https://github.com/alexmercerind/flutter_audio_desktop/blob/master/README.md

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterAudioDesktopPlugin
      windows:
        pluginClass: FlutterAudioDesktopPlugin